Dev
AlexEKB/fake_livejournal pull request #1
Opened 2019-01-15 18:22 UTC by AlexEKB

•	Создание нового аккаунта
•	Вход в аккаунт с помощью почты и пароля
•	Восстановление пароля
•	Редактирование почты и пароля
•	Вход и регистрация через гугл аккаунт

2019-01-16 13:10 UTC, ghost requested changes

2019-01-16 13:10 UTC, vladimirbazhanov commented on Gemfile.lock
> +    bcrypt (3.1.12-x86-mingw32)
java и mingw выглядят будто тут не нужны

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
Pls remove empty files and files that contains only comments, they must not be in repo

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/assets/javascripts/users/omniauth_callbacks.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
and here

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/assets/stylesheets/application.css
> + */
pls setup your editor to automatically add empty newline at the file end

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/assets/stylesheets/bootstrap_and_overrides.css
> +*/
and here

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/assets/stylesheets/scaffolds.scss
> +body {
remove this file, it will overrride bootstrap styles

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/assets/stylesheets/users.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
remove this file

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/assets/stylesheets/users/omniauth_callbacks.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
and this

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/controllers/application_controller.rb
> +      u.permit(:email, :password, :password_confirmation, :current_password, :provider, :uid)
I think you should not enable updating :provider and :uid

This fields must not be updatable from user interface

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/controllers/users_controller.rb
> +  # GET /users.json
pls remove autogenerated comments

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/controllers/users_controller.rb
> +        format.json { render :show, status: :created, location: @user }
pls remove format.json line, it seems that it is not used

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/controllers/users_controller.rb
> +        format.json { render json: @user.errors, status: :unprocessable_entity }
and here

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/controllers/users_controller.rb
> +        format.json { render :show, status: :ok, location: @user }
and here)

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/controllers/users_controller.rb
> +      params.require(:user).permit(:email, :encrypted_password, :password, :provider, :uid)
remove from here 'provider' and 'uid'

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/helpers/users/omniauth_callbacks_helper.rb
> +end
empty file, pls remove it

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/views/users/_user.json.jbuilder
> +json.url user_url(user, format: :json)
remove this, it's not used

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/views/users/edit.html.erb
> +<%= link_to 'Back', users_path %>
It would be great if you install gem 'slim-rails' and re-create all .erb views using SLIM

2019-01-16 13:10 UTC, vladimirbazhanov commented on app/views/users/show.json.jbuilder
> +json.partial! "users/user", user: @user
this can be removed

2019-01-16 13:10 UTC, vladimirbazhanov commented on config/environments/development.rb
> +      enable_starttls_auto: true
pls remove this, you never should use real email sending in development!

2019-01-16 13:10 UTC, vladimirbazhanov commented on db/migrate/20190115072258_create_users.rb
> +
this migration is empty :)

2019-01-16 13:10 UTC, vladimirbazhanov commented on test/controllers/users/omniauth_callbacks_controller_test.rb
> +end
we prefer to not user default Rails' tests, pls remove them

2019-01-16 13:10 UTC, vladimirbazhanov commented on test/controllers/users_controller_test.rb
> +end
We'll replace this with specs using RSpec, so pls remove it

2019-01-16 13:45 UTC, AlexEKB commented on Gemfile.lock
> +    bcrypt (3.1.12-x86-mingw32)
не совсем понял, что нужно сделать, я эту библиотеку не добавлял, она по умолчанию включилась в лок

2019-01-16 14:51 UTC, AlexEKB commented on app/assets/stylesheets/application.css
> + */
не совсем понимаю, что нужно сделать

2019-01-16 14:51 UTC, AlexEKB commented on app/assets/stylesheets/bootstrap_and_overrides.css
> +*/
не совсем понимаю, что нужно сделать

2019-01-16 14:51 UTC, AlexEKB commented on db/migrate/20190115072258_create_users.rb
> +
файл миграции удалить?

2019-01-24 10:32 UTC, vladimirbazhanov commented on Gemfile.lock
> +    bcrypt (3.1.12-x86-mingw32)
Мысль была такая: java, mingw32 это платформы, на которых может быть запущен этот гем, было бы хорошо погуглить иразобраться, как добавить в гемфайл то, что его притащило нам, указав при этом, что мы юзаем только платформу linux

2019-01-24 10:34 UTC, vladimirbazhanov commented on app/controllers/comments_controller.rb
> +        format.html {redirect_to @post, notice: 'Комментарий успешно создан.'}
когда контроллер может отвечать только одним форматом ответа так сказать, можно не писать format, то есть

if @new_comment.save
  redirect_to @post, notice: 'Комментарий успешно создан.'
else
  render "posts/show"
end

2019-01-24 10:35 UTC, vladimirbazhanov commented on app/helpers/comments_helper.rb
> +end
пустые хелперы плз удали

2019-01-24 10:36 UTC, vladimirbazhanov commented on app/views/comments/show.html.slim
> +p#notice = notice
лишний нотис сгенерировался

2019-01-24 10:39 UTC, vladimirbazhanov commented on db/migrate/20190115072258_create_users.rb
> +
нет, я имел ввиду, что миграция не должна быть пустой, ведь если ей зпустить пустую - она не создат таблицу Users и колонки в ней

2019-01-24 10:39 UTC, vladimirbazhanov commented on db/migrate/20190115072258_create_users.rb
> +
ну в общем, да, хотя бы удали её

2019-01-24 11:35 UTC, AlexEKB commented on Gemfile.lock
> +    bcrypt (3.1.12-x86-mingw32)
добавил в гемфайл gem 'bcrypt', '3.1.12', platforms: [:ruby] , т.к. linux в списке доступных платформ не нашёл. 
The available options are: [:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :ruby_24, :ruby_25, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :mri_24, :mri_25, :rbx, :truffleruby, :jruby, :jruby_18, :jruby_19, :mswin, :mswin_18, :mswin_19, :mswin_20, :mswin_21, :mswin_22, :mswin_23, :mswin_24, :mswin_25, :mswin64, :mswin64_19, :mswin64_20, :mswin64_21, :mswin64_22, :mswin64_23, :mswin64_24, :mswin64_25, :mingw, :mingw_18, :mingw_19, :mingw_20, :mingw_21, :mingw_22, :mingw_23, :mingw_24, :mingw_25, :x64_mingw, :x64_mingw_20, :x64_mingw_21, :x64_mingw_22, :x64_mingw_23, :x64_mingw_24, :x64_mingw_25].

2019-01-28 15:52 UTC, ghost approved these changes

2019-01-28 17:10 UTC, merged